# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-EP3
version:      1.10
version_from: lib/Text/EP3.pm
installdirs:  site
requires:
    AutoLoader:                    0
    Carp:                          0
    Cwd:                           0
    Env:                           0
    Exporter:                      0
    FileHandle:                    0
    Getopt::Long:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
